on: [push]

jobs:
  build-and-deploy:
    name: Build and Deploy
    container:
      image: node
    runs-on: ubuntu-latest
    steps:
      - name: Login to docker hub
        uses: actions-hub/docker/login@master
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_ACCESS_TOKEN }}

      - name: Build :latest
        run: docker build -t personal-website:latest .

      - name: Push to docker hub :latest
        uses: actions-hub/docker@master
        with:
          args: push personal-website:latest
