on: [push]

jobs:
  build-and-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    steps:
      - 
        uses: actions/checkout@v2.3.2
      - name: The Docker CLI
        # You may pin to the exact commit or the version.
        # uses: actions-hub/docker@726e89023248c002cf9aadfc8b8364687a3ed25f
        uses: actions-hub/docker@v1.0.0
        with:
          # Docker image (if not the same as repo)
          NAME: personal-website
          # Docker tag (if want to specify tag)
          TAG: ngoble.azurecr.io/personal/website
          # Docker username
          DOCKER_USERNAME: ${{ secrets.AZURE_USERNAME }}
          # Docker password
          DOCKER_PASSWORD: ${{ secrets.AZURE_PASSWORD }}
          # Docker registry url
          DOCKER_REGISTRY_URL: ngoble.azurecr.io
      - 
        name: Build and push
        id: docker_build
        env:
          DOCKER_CONFIG: ${{ steps.acr_login.outputs.DOCKER_CONFIG }} 
        run: docker build -t personal-website .
      -
        name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
