on: [push]

jobs:
  build-and-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    steps:
      - 
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - 
        name: Azure Container Registry Login
        id: acr_login
        uses: Azure/docker-login@v1
        with:
          # Container registry username
          username: ${{ secrets.AZURE_USERNAME }}
          # Container registry password
          password: ${{ secrets.AZURE_PASSWORD }} 
          # Container registry server url
          login-server: ngoble.azurecr.io
      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: personal-website:latest
      -
        name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
